/** Tokens portados 1:1 del design system "MarketMind AI" (DOCS/.../DESIGN.md)
 * para reusar el mockup del compañero como base real del frontend. */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#dae2fd",
        "on-tertiary-container": "#eef0ff",
        "surface-container-lowest": "#070e1c",
        "secondary-fixed": "#dce2f7",
        "secondary-container": "#404758",
        "inverse-primary": "#0053db",
        "on-secondary-container": "#aeb5c9",
        surface: "#0c1321",
        "inverse-on-surface": "#2a3040",
        "on-secondary-fixed": "#141b2b",
        "error-container": "#93000a",
        "surface-variant": "#2e3544",
        "on-surface-variant": "#c3c6d7",
        "tertiary-container": "#656d84",
        "outline-variant": "#434655",
        secondary: "#c0c6db",
        "on-secondary-fixed-variant": "#404758",
        "surface-bright": "#323949",
        "surface-dim": "#0c1321",
        "on-tertiary": "#283044",
        "surface-tint": "#b4c5ff",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#bec6e0",
        "on-primary-container": "#eeefff",
        "primary-container": "#2563eb",
        "on-primary-fixed": "#00174b",
        "secondary-fixed-dim": "#c0c6db",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-error-container": "#ffdad6",
        "on-primary": "#002a78",
        "inverse-surface": "#dce2f6",
        "on-error": "#690005",
        "surface-container-highest": "#2e3544",
        primary: "#b4c5ff",
        background: "#0c1321",
        "on-surface": "#dce2f6",
        "surface-container-high": "#232a39",
        "on-tertiary-fixed": "#131b2e",
        "surface-container-low": "#151b2a",
        "surface-container": "#19202e",
        tertiary: "#bec6e0",
        "on-secondary": "#293040",
        "on-primary-fixed-variant": "#003ea8",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-background": "#dce2f6",
        outline: "#8d90a0",
        success: "#7dd88f",
        "on-success": "#0a3d17",
        warning: "#f5c065",
        "on-warning": "#402d00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        "container-padding": "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
